spring:
  application:
    name: my-blog-back-app
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cors:
    allowed:
      origins: ${SPRING_CORS_ALLOWED_ORIGINS}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    ru:
      practicum: ${LOGGING_PRACTICUM_LEVEL}}
